In [1]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statistics import mean

# reading the file
df1 = pd.read_csv("ADMISSIONS.csv.gz")

# printing the first 5 rows of the data frame
df1.head()

,ROW_ID,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,DEATHTIME,ADMISSION_TYPE,ADMISSION_LOCATION,DISCHARGE_LOCATION,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA
0,21,22,165315,2196-04-09 12:26:00,2196-04-10 15:54:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,DISC-TRAN CANCER/CHLDRN H,Private,NaN,UNOBTAINABLE,MARRIED,WHITE,2196-04-09 10:06:00,2196-04-09 13:24:00,BENZODIAZEPINE OVERDOSE,0,1
1,22,23,152223,2153-09-03 07:15:00,2153-09-08 19:10:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,HOME HEALTH CARE,Medicare,NaN,CATHOLIC,MARRIED,WHITE,NaN,NaN,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,0,1
2,23,23,124321,2157-10-18 19:34:00,2157-10-25 14:00:00,NaN,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME HEALTH CARE,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,NaN,NaN,BRAIN MASS,0,1
3,24,24,161859,2139-06-06 16:14:00,2139-06-09 12:48:00,NaN,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME,Private,NaN,PROTESTANT QUAKER,SINGLE,WHITE,NaN,NaN,INTERIOR MYOCARDIAL INFARCTION,0,1
4,25,25,129635,2160-11-02 02:06:00,2160-11-05 14:55:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Private,NaN,UNOBTAINABLE,MARRIED,WHITE,2160-11-02 01:01:00,2160-11-02 04:27:00,ACUTE CORONARY SYNDROME,0,1

In [2]:
df1.shape

(58976, 19)

In [3]:
# removing the rows with no 'subjectID'
df1 = df1[df1["SUBJECT_ID"].notnull()]
df1.shape

(58976, 19)

In [4]:
df1["DIAGNOSIS"].value_counts(dropna = False)

NEWBORN                                                7823
PNEUMONIA                                              1566
SEPSIS                                                 1184
CONGESTIVE HEART FAILURE                                928
CORONARY ARTERY DISEASE                                 840
                                                       ...
CORONARY ARTERY DISEASE;PVD                               1
ASCITES-SHORTNESS OF BREATH                               1
ABDOMINAL AORTIC ANEURYSM;                                1
.\VENTRICULAR TACHYCARDIA ABLATION  **REMOTE WEST**       1
WEAKNESS;RULE-OUT MYOCARDIAL INFARCTION                   1
Name: DIAGNOSIS, Length: 15692, dtype: int64

In [5]:
df1.ADMISSION_TYPE.value_counts()

EMERGENCY    42071
NEWBORN       7863
ELECTIVE      7706
URGENT        1336
Name: ADMISSION_TYPE, dtype: int64

In [6]:
df1.isna().sum()

ROW_ID                      0
SUBJECT_ID                  0
HADM_ID                     0
ADMITTIME                   0
DISCHTIME                   0
DEATHTIME               53122
ADMISSION_TYPE              0
ADMISSION_LOCATION          0
DISCHARGE_LOCATION          0
INSURANCE                   0
LANGUAGE                25332
RELIGION                  458
MARITAL_STATUS          10128
ETHNICITY                   0
EDREGTIME               28099
EDOUTTIME               28099
DIAGNOSIS                  25
HOSPITAL_EXPIRE_FLAG        0
HAS_CHARTEVENTS_DATA        0
dtype: int64

In [7]:
df1 = df1[df1['DIAGNOSIS'].notna()]

In [8]:
df1.isna().sum()

ROW_ID                      0
SUBJECT_ID                  0
HADM_ID                     0
ADMITTIME                   0
DISCHTIME                   0
DEATHTIME               53098
ADMISSION_TYPE              0
ADMISSION_LOCATION          0
DISCHARGE_LOCATION          0
INSURANCE                   0
LANGUAGE                25322
RELIGION                  458
MARITAL_STATUS          10127
ETHNICITY                   0
EDREGTIME               28075
EDOUTTIME               28075
DIAGNOSIS                   0
HOSPITAL_EXPIRE_FLAG        0
HAS_CHARTEVENTS_DATA        0
dtype: int64

In [9]:
df1 = df1[df1.DIAGNOSIS.str.contains('SEPSIS')]
df1.shape

(1783, 19)

In [10]:
df1 = df1[df1["DIAGNOSIS"] == "SEPSIS"]
df1.drop('ROW_ID', axis=1, inplace = True)
df1.head(10)

,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,DEATHTIME,ADMISSION_TYPE,ADMISSION_LOCATION,DISCHARGE_LOCATION,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA
24,357,122609,2198-11-01 22:36:00,2198-11-14 14:20:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,REHAB/DISTINCT PART HOSP,Private,ENGL,NOT SPECIFIED,MARRIED,WHITE,2198-11-01 18:01:00,2198-11-01 23:06:00,SEPSIS,0,1
37,366,134462,2164-11-18 20:27:00,2164-11-22 15:18:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicare,ENGL,CATHOLIC,SINGLE,HISPANIC OR LATINO,2164-11-18 10:52:00,2164-11-18 21:31:00,SEPSIS,0,1
98,94,183686,2176-02-25 16:49:00,2176-02-29 17:45:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicare,CANT,NOT SPECIFIED,MARRIED,ASIAN,2176-02-25 10:35:00,2176-02-25 18:14:00,SEPSIS,0,1
230,21,111970,2135-01-30 20:50:00,2135-02-08 02:08:00,2135-02-08 02:08:00,EMERGENCY,EMERGENCY ROOM ADMIT,DEAD/EXPIRED,Medicare,NaN,JEWISH,MARRIED,WHITE,2135-01-30 18:46:00,2135-01-30 22:05:00,SEPSIS,1,1
300,353,108923,2151-03-28 16:01:00,2151-04-13 16:10:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Medicare,PTUN,JEWISH,SINGLE,WHITE,2151-03-28 13:02:00,2151-03-28 17:46:00,SEPSIS,0,1
302,353,131488,2151-10-01 20:42:00,2151-10-20 15:20:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Medicare,PTUN,JEWISH,SINGLE,WHITE,2151-10-01 10:36:00,2151-10-01 21:04:00,SEPSIS,0,1
363,507,148905,2146-06-22 00:58:00,2146-07-05 11:58:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicare,NaN,CATHOLIC,MARRIED,WHITE,2146-06-21 20:28:00,2146-06-22 02:42:00,SEPSIS,0,1
409,406,113900,2119-08-25 22:37:00,2119-09-01 18:00:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME WITH HOME IV PROVIDR,Medicaid,NaN,CATHOLIC,MARRIED,WHITE,2119-08-25 17:00:00,2119-08-26 01:52:00,SEPSIS,0,1
410,406,171178,2120-09-17 05:03:00,2120-09-28 12:15:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,REHAB/DISTINCT PART HOSP,Medicaid,ENGL,CATHOLIC,MARRIED,WHITE,2120-09-17 03:29:00,2120-09-17 10:08:00,SEPSIS,0,1
412,406,100765,2126-03-11 23:06:00,2126-03-26 16:17:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,LONG TERM CARE HOSPITAL,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,2126-03-11 19:28:00,2126-03-12 00:02:00,SEPSIS,0,1

In [11]:
df1.shape

(1184, 18)

In [12]:
df1["ADMITTIME"]= pd.to_datetime(df1["ADMITTIME"])
df1["DISCHTIME"]= pd.to_datetime(df1["DISCHTIME"])

In [13]:
df1 = df1.loc[(df1['DISCHTIME'] - df1['ADMITTIME']) >= pd.Timedelta(hours=48)]    
print(df1.shape)
df1

(1067, 18)

,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,DEATHTIME,ADMISSION_TYPE,ADMISSION_LOCATION,DISCHARGE_LOCATION,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA
24,357,122609,2198-11-01 22:36:00,2198-11-14 14:20:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,REHAB/DISTINCT PART HOSP,Private,ENGL,NOT SPECIFIED,MARRIED,WHITE,2198-11-01 18:01:00,2198-11-01 23:06:00,SEPSIS,0,1
37,366,134462,2164-11-18 20:27:00,2164-11-22 15:18:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicare,ENGL,CATHOLIC,SINGLE,HISPANIC OR LATINO,2164-11-18 10:52:00,2164-11-18 21:31:00,SEPSIS,0,1
98,94,183686,2176-02-25 16:49:00,2176-02-29 17:45:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicare,CANT,NOT SPECIFIED,MARRIED,ASIAN,2176-02-25 10:35:00,2176-02-25 18:14:00,SEPSIS,0,1
230,21,111970,2135-01-30 20:50:00,2135-02-08 02:08:00,2135-02-08 02:08:00,EMERGENCY,EMERGENCY ROOM ADMIT,DEAD/EXPIRED,Medicare,NaN,JEWISH,MARRIED,WHITE,2135-01-30 18:46:00,2135-01-30 22:05:00,SEPSIS,1,1
300,353,108923,2151-03-28 16:01:00,2151-04-13 16:10:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Medicare,PTUN,JEWISH,SINGLE,WHITE,2151-03-28 13:02:00,2151-03-28 17:46:00,SEPSIS,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58852,96261,150731,2196-03-27 17:05:00,2196-04-08 12:40:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME HEALTH CARE,Private,ENGL,NOT SPECIFIED,MARRIED,WHITE,2196-03-27 15:00:00,2196-03-27 18:59:00,SEPSIS,0,1
58860,90688,112686,2154-11-09 11:29:00,2154-11-13 17:30:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,LONG TERM CARE HOSPITAL,Medicare,ENGL,CATHOLIC,WIDOWED,WHITE,2154-11-09 05:33:00,2154-11-09 12:50:00,SEPSIS,0,1
58890,95372,181449,2124-04-17 16:11:00,2124-04-24 15:38:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME HEALTH CARE,Medicare,SPAN,OTHER,MARRIED,HISPANIC OR LATINO,2124-04-17 09:52:00,2124-04-17 17:17:00,SEPSIS,0,1
58934,98698,134977,2188-10-18 02:00:00,2188-10-22 15:53:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Government,ENGL,CATHOLIC,MARRIED,WHITE,2188-10-17 22:01:00,2188-10-18 03:27:00,SEPSIS,0,1
58951,98744,153703,2127-10-21 12:43:00,2127-10-31 12:35:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME HEALTH CARE,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,NaN,NaN,SEPSIS,0,1

In [14]:
df1.drop(['ADMISSION_LOCATION','DISCHARGE_LOCATION','INSURANCE','LANGUAGE','RELIGION',
          'MARITAL_STATUS','ETHNICITY','EDREGTIME','EDOUTTIME'], axis=1, inplace = True)

In [15]:
print(df1.HOSPITAL_EXPIRE_FLAG.value_counts())
print(df1.ADMISSION_TYPE.value_counts())

0    892
1    175
Name: HOSPITAL_EXPIRE_FLAG, dtype: int64
EMERGENCY    1055
URGENT         12
Name: ADMISSION_TYPE, dtype: int64

In [16]:
df1.head()

,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,DEATHTIME,ADMISSION_TYPE,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA
24,357,122609,2198-11-01 22:36:00,2198-11-14 14:20:00,NaN,EMERGENCY,SEPSIS,0,1
37,366,134462,2164-11-18 20:27:00,2164-11-22 15:18:00,NaN,EMERGENCY,SEPSIS,0,1
98,94,183686,2176-02-25 16:49:00,2176-02-29 17:45:00,NaN,EMERGENCY,SEPSIS,0,1
230,21,111970,2135-01-30 20:50:00,2135-02-08 02:08:00,2135-02-08 02:08:00,EMERGENCY,SEPSIS,1,1
300,353,108923,2151-03-28 16:01:00,2151-04-13 16:10:00,NaN,EMERGENCY,SEPSIS,0,1

In [17]:
df1.dtypes

SUBJECT_ID                       int64
HADM_ID                          int64
ADMITTIME               datetime64[ns]
DISCHTIME               datetime64[ns]
DEATHTIME                       object
ADMISSION_TYPE                  object
DIAGNOSIS                       object
HOSPITAL_EXPIRE_FLAG             int64
HAS_CHARTEVENTS_DATA             int64
dtype: object

In [18]:
list_ID = df1['SUBJECT_ID'].to_list()
l= len(list_ID)

In [19]:
temp_cv = 'INPUTEVENTS_CV.csv.gz'

In [20]:
def filterInputEvent_SubjectID(data,list_ID):
    list_1 = data['SUBJECT_ID'].isin(list_ID).tolist()
    d1 = data[list_1] 
    return d1

In [21]:
chunks_input_cv = []
for chunk in pd.read_csv(temp_cv, chunksize = 100000):
    chunks_input_cv.append(filterInputEvent_SubjectID(chunk, list_ID))

C:\Users\admin\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (20) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\admin\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (20,21) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\admin\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (21) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\admin\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (9,21) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\admin\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\admin\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (7,9,17,20,21) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\admin\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (7,17,20,21) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\admin\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [22]:
df_input_cv=pd.concat(chunks_input_cv)
df_input_cv.shape

(1023154, 22)

In [23]:
df_input_cv.columns

Index(['ROW_ID', 'SUBJECT_ID', 'HADM_ID', 'ICUSTAY_ID', 'CHARTTIME', 'ITEMID',
       'AMOUNT', 'AMOUNTUOM', 'RATE', 'RATEUOM', 'STORETIME', 'CGID',
       'ORDERID', 'LINKORDERID', 'STOPPED', 'NEWBOTTLE', 'ORIGINALAMOUNT',
       'ORIGINALAMOUNTUOM', 'ORIGINALROUTE', 'ORIGINALRATE', 'ORIGINALRATEUOM',
       'ORIGINALSITE'],
      dtype='object')

In [24]:
df_input_cv.drop(['ROW_ID',  'ICUSTAY_ID', 'STORETIME', 'CGID',
       'ORDERID', 'LINKORDERID', 'STOPPED', 'NEWBOTTLE', 'ORIGINALAMOUNT',
       'ORIGINALAMOUNTUOM', 'ORIGINALROUTE', 'ORIGINALRATE', 'ORIGINALRATEUOM',
       'ORIGINALSITE'], axis=1, inplace = True)

In [25]:
df_input_cv.head()

,SUBJECT_ID,HADM_ID,CHARTTIME,ITEMID,AMOUNT,AMOUNTUOM,RATE,RATEUOM
342,11318,178137.0,2119-09-21 17:00:00,30056,0.0,ml,NaN,NaN
343,11318,178137.0,2119-09-21 18:00:00,30056,120.0,ml,NaN,NaN
344,11318,178137.0,2119-09-22 10:00:00,30056,200.0,ml,NaN,NaN
345,11318,178137.0,2119-09-22 21:00:00,30056,240.0,ml,NaN,NaN
346,11318,178137.0,2119-09-22 22:00:00,30056,200.0,ml,NaN,NaN

In [26]:
df_input_cv.rename(columns={'CHARTTIME':'ENDTIME'}, inplace=True)

In [27]:
df_input_cv.dtypes

SUBJECT_ID      int64
HADM_ID       float64
ENDTIME        object
ITEMID          int64
AMOUNT        float64
AMOUNTUOM      object
RATE          float64
RATEUOM        object
dtype: object

In [28]:
df_input_cv.isna().sum()

SUBJECT_ID         0
HADM_ID          542
ENDTIME            0
ITEMID             0
AMOUNT        274640
AMOUNTUOM     264040
RATE          768941
RATEUOM       766347
dtype: int64

In [29]:
df_input_cv = df_input_cv.dropna(subset=['HADM_ID'])

In [30]:
df_input_cv['HADM_ID'] = df_input_cv.HADM_ID.astype(int)

In [31]:
temp_mv = 'INPUTEVENTS_MV.csv.gz'

In [32]:
chunks_input_mv = []
for chunk in pd.read_csv(temp_mv, chunksize = 100000):
    chunks_input_mv.append(filterInputEvent_SubjectID(chunk, list_ID))

In [33]:
df_input_mv=pd.concat(chunks_input_mv)
df_input_mv.shape

(199996, 31)

In [34]:
df_input_mv.columns

Index(['ROW_ID', 'SUBJECT_ID', 'HADM_ID', 'ICUSTAY_ID', 'STARTTIME', 'ENDTIME',
       'ITEMID', 'AMOUNT', 'AMOUNTUOM', 'RATE', 'RATEUOM', 'STORETIME', 'CGID',
       'ORDERID', 'LINKORDERID', 'ORDERCATEGORYNAME',
       'SECONDARYORDERCATEGORYNAME', 'ORDERCOMPONENTTYPEDESCRIPTION',
       'ORDERCATEGORYDESCRIPTION', 'PATIENTWEIGHT', 'TOTALAMOUNT',
       'TOTALAMOUNTUOM', 'ISOPENBAG', 'CONTINUEINNEXTDEPT', 'CANCELREASON',
       'STATUSDESCRIPTION', 'COMMENTS_EDITEDBY', 'COMMENTS_CANCELEDBY',
       'COMMENTS_DATE', 'ORIGINALAMOUNT', 'ORIGINALRATE'],
      dtype='object')

In [35]:
df_input_mv.drop(['ROW_ID', 'ICUSTAY_ID', 'STARTTIME','STORETIME', 'CGID',
       'ORDERID', 'LINKORDERID', 'ORDERCATEGORYNAME',
       'SECONDARYORDERCATEGORYNAME', 'ORDERCOMPONENTTYPEDESCRIPTION',
       'ORDERCATEGORYDESCRIPTION', 'TOTALAMOUNT',
       'TOTALAMOUNTUOM', 'ISOPENBAG', 'CONTINUEINNEXTDEPT', 'CANCELREASON',
       'STATUSDESCRIPTION', 'COMMENTS_EDITEDBY', 'COMMENTS_CANCELEDBY',
       'COMMENTS_DATE', 'ORIGINALAMOUNT', 'ORIGINALRATE'], axis=1, inplace = True)

In [36]:
df_input_mv.head()

,SUBJECT_ID,HADM_ID,ENDTIME,ITEMID,AMOUNT,AMOUNTUOM,RATE,RATEUOM,PATIENTWEIGHT
187,29054,191001,2147-02-08 23:05:00,225158,250.000005,ml,10.0,mL/hour,72.7
188,29054,191001,2147-02-07 18:01:00,226452,120.000000,ml,NaN,NaN,72.7
189,29054,191001,2147-02-07 22:05:00,225837,1.000000,dose,NaN,NaN,72.7
190,29054,191001,2147-02-07 22:05:00,220949,100.000000,ml,NaN,NaN,72.7
191,29054,191001,2147-02-07 16:00:00,225158,60.000000,ml,15.0,mL/hour,72.7

In [37]:
df_input_mv.dtypes

SUBJECT_ID         int64
HADM_ID            int64
ENDTIME           object
ITEMID             int64
AMOUNT           float64
AMOUNTUOM         object
RATE             float64
RATEUOM           object
PATIENTWEIGHT    float64
dtype: object

In [38]:
INPUT = pd.concat([df_input_cv, df_input_mv], axis=0)
INPUT = INPUT.reset_index(drop=True)
INPUT.head

<bound method NDFrame.head of          SUBJECT_ID  HADM_ID              ENDTIME  ITEMID   AMOUNT AMOUNTUOM  \
0             11318   178137  2119-09-21 17:00:00   30056     0.00        ml
1             11318   178137  2119-09-21 18:00:00   30056   120.00        ml
2             11318   178137  2119-09-22 10:00:00   30056   200.00        ml
3             11318   178137  2119-09-22 21:00:00   30056   240.00        ml
4             11318   178137  2119-09-22 22:00:00   30056   200.00        ml
...             ...      ...                  ...     ...      ...       ...
1222603       51596   104252  2119-07-13 12:53:00  225158  1000.00        ml
1222604       51596   104252  2119-07-13 14:56:00  221833     0.50        mg
1222605       51596   104252  2119-07-14 00:31:00  226453   100.00        ml
1222606       51596   104252  2119-07-14 00:25:00  225936   105.25        ml
1222607       51596   104252  2119-07-14 12:01:00  225883     1.00      dose

         RATE  RATEUOM  PATIENTWEIGHT
0         NaN      NaN            NaN
1         NaN      NaN            NaN
2         NaN      NaN            NaN
3         NaN      NaN            NaN
4         NaN      NaN            NaN
...       ...      ...            ...
1222603   NaN      NaN           61.0
1222604   NaN      NaN           61.0
1222605   NaN      NaN           61.0
1222606  15.0  mL/hour           61.0
1222607   NaN      NaN           61.0

[1222608 rows x 9 columns]>

In [39]:
INPUT.columns

Index(['SUBJECT_ID', 'HADM_ID', 'ENDTIME', 'ITEMID', 'AMOUNT', 'AMOUNTUOM',
       'RATE', 'RATEUOM', 'PATIENTWEIGHT'],
      dtype='object')

In [40]:
dfx = pd.read_csv("D_ITEMS.csv.gz")

# printing the first 5 rows of the data frame
dfx.head()

,ROW_ID,ITEMID,LABEL,ABBREVIATION,DBSOURCE,LINKSTO,CATEGORY,UNITNAME,PARAM_TYPE,CONCEPTID
0,457,497,Patient controlled analgesia (PCA) [Inject],NaN,carevue,chartevents,NaN,NaN,NaN,NaN
1,458,498,PCA Lockout (Min),NaN,carevue,chartevents,NaN,NaN,NaN,NaN
2,459,499,PCA Medication,NaN,carevue,chartevents,NaN,NaN,NaN,NaN
3,460,500,PCA Total Dose,NaN,carevue,chartevents,NaN,NaN,NaN,NaN
4,461,501,PCV Exh Vt (Obser),NaN,carevue,chartevents,NaN,NaN,NaN,NaN

In [41]:
dfx = dfx[['ITEMID', 'LABEL']]

In [42]:
print(len('ITEMID'))

6

In [43]:
Input1 = pd.merge(INPUT, dfx, on=['ITEMID'])
Input1.head()

,SUBJECT_ID,HADM_ID,ENDTIME,ITEMID,AMOUNT,AMOUNTUOM,RATE,RATEUOM,PATIENTWEIGHT,LABEL
0,11318,178137,2119-09-21 17:00:00,30056,0.0,ml,NaN,NaN,NaN,Po Intake
1,11318,178137,2119-09-21 18:00:00,30056,120.0,ml,NaN,NaN,NaN,Po Intake
2,11318,178137,2119-09-22 10:00:00,30056,200.0,ml,NaN,NaN,NaN,Po Intake
3,11318,178137,2119-09-22 21:00:00,30056,240.0,ml,NaN,NaN,NaN,Po Intake
4,11318,178137,2119-09-22 22:00:00,30056,200.0,ml,NaN,NaN,NaN,Po Intake

In [44]:
Input1.dtypes

SUBJECT_ID         int64
HADM_ID            int64
ENDTIME           object
ITEMID             int64
AMOUNT           float64
AMOUNTUOM         object
RATE             float64
RATEUOM           object
PATIENTWEIGHT    float64
LABEL             object
dtype: object

In [45]:
Input2 = pd.merge(Input1, df1, on=['SUBJECT_ID','HADM_ID'])

In [46]:
Input2.head()

,SUBJECT_ID,HADM_ID,ENDTIME,ITEMID,AMOUNT,AMOUNTUOM,RATE,RATEUOM,PATIENTWEIGHT,LABEL,ADMITTIME,DISCHTIME,DEATHTIME,ADMISSION_TYPE,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA
0,2488,117965,2136-08-15 09:00:00,30056,150.0,ml,NaN,NaN,NaN,Po Intake,2136-07-31 20:43:00,2136-08-24 15:58:00,NaN,EMERGENCY,SEPSIS,0,1
1,2488,117965,2136-08-15 11:00:00,30056,240.0,ml,NaN,NaN,NaN,Po Intake,2136-07-31 20:43:00,2136-08-24 15:58:00,NaN,EMERGENCY,SEPSIS,0,1
2,2488,117965,2136-08-15 12:00:00,30056,120.0,ml,NaN,NaN,NaN,Po Intake,2136-07-31 20:43:00,2136-08-24 15:58:00,NaN,EMERGENCY,SEPSIS,0,1
3,2488,117965,2136-08-15 14:00:00,30056,120.0,ml,NaN,NaN,NaN,Po Intake,2136-07-31 20:43:00,2136-08-24 15:58:00,NaN,EMERGENCY,SEPSIS,0,1
4,2488,117965,2136-08-15 18:00:00,30056,120.0,ml,NaN,NaN,NaN,Po Intake,2136-07-31 20:43:00,2136-08-24 15:58:00,NaN,EMERGENCY,SEPSIS,0,1

In [47]:
Input2.columns

Index(['SUBJECT_ID', 'HADM_ID', 'ENDTIME', 'ITEMID', 'AMOUNT', 'AMOUNTUOM',
       'RATE', 'RATEUOM', 'PATIENTWEIGHT', 'LABEL', 'ADMITTIME', 'DISCHTIME',
       'DEATHTIME', 'ADMISSION_TYPE', 'DIAGNOSIS', 'HOSPITAL_EXPIRE_FLAG',
       'HAS_CHARTEVENTS_DATA'],
      dtype='object')

In [48]:
Input2.drop(['DEATHTIME',
       'ADMISSION_TYPE', 'DIAGNOSIS', 'HOSPITAL_EXPIRE_FLAG',
       'HAS_CHARTEVENTS_DATA'], axis=1, inplace = True)

In [49]:
# overwriting data after changing format
Input2["DISCHTIME"]= pd.to_datetime(Input2["DISCHTIME"])
Input2["ENDTIME"]= pd.to_datetime(Input2["ENDTIME"])

In [50]:
Input3 = Input2.loc[(Input2['DISCHTIME'] - Input2['ENDTIME']) <= pd.Timedelta(hours=48)]    
print(Input3.shape)
Input3

(39568, 12)

,SUBJECT_ID,HADM_ID,ENDTIME,ITEMID,AMOUNT,AMOUNTUOM,RATE,RATEUOM,PATIENTWEIGHT,LABEL,ADMITTIME,DISCHTIME
4355,590,172260,2124-11-15 09:00:00,30013,100.0,ml,NaN,NaN,NaN,D5W,2124-11-02 08:56:00,2124-11-15 18:29:00
4356,590,172260,2124-11-15 10:00:00,30013,50.0,ml,NaN,NaN,NaN,D5W,2124-11-02 08:56:00,2124-11-15 18:29:00
4357,590,172260,2124-11-15 14:00:00,30013,100.0,ml,NaN,NaN,NaN,D5W,2124-11-02 08:56:00,2124-11-15 18:29:00
4476,590,172260,2124-11-14 23:00:00,30013,35.0,ml,NaN,NaN,NaN,D5W,2124-11-02 08:56:00,2124-11-15 18:29:00
4477,590,172260,2124-11-15 01:30:00,30013,87.5,ml,NaN,NaN,NaN,D5W,2124-11-02 08:56:00,2124-11-15 18:29:00
...,...,...,...,...,...,...,...,...,...,...,...,...
626950,41284,121591,2155-07-20 20:01:00,225975,1.0,dose,NaN,NaN,97.5,Heparin Sodium (Prophylaxis),2155-07-19 20:19:00,2155-07-22 20:00:00
627589,31361,127631,2180-11-20 17:12:00,226452,60.0,ml,NaN,NaN,49.8,PO Intake,2180-11-19 12:30:00,2180-11-22 15:15:00
627596,31361,127631,2180-11-20 20:25:00,220949,100.0,ml,NaN,NaN,49.8,Dextrose 5%,2180-11-19 12:30:00,2180-11-22 15:15:00
627602,31361,127631,2180-11-20 20:25:00,225893,1.0,dose,NaN,NaN,49.8,Piperacillin/Tazobactam (Zosyn),2180-11-19 12:30:00,2180-11-22 15:15:00
627606,31361,127631,2180-11-20 16:01:00,225975,1.0,dose,NaN,NaN,49.8,Heparin Sodium (Prophylaxis),2180-11-19 12:30:00,2180-11-22 15:15:00

In [51]:
H_ID = Input3['HADM_ID'].unique().tolist()
print(H_ID)
print(len(H_ID))

[172260, 146995, 193149, 179287, 103904, 114345, 148158, 185483, 103195, 101184, 183920, 151003, 155281, 150778, 122293, 103778, 158408, 149043, 112560, 184219, 118985, 147012, 138331, 185100, 181158, 129493, 188196, 168094, 144017, 123912, 177199, 161064, 189199, 166956, 137772, 158183, 175586, 194424, 148295, 179519, 193274, 114997, 186968, 186821, 182589, 185758, 116181, 156972, 111109, 169217, 122915, 104329, 115662, 188392, 169557, 122982, 123040, 151652, 170984, 190582, 107286, 148365, 102847, 173681, 111970, 149844, 135251, 156400, 171681, 189051, 162875, 160080, 147319, 153858, 171106, 150506, 121097, 170106, 147119, 175912, 151808, 189131, 104141, 105557, 154361, 146426, 159459, 195303, 134462, 146738, 108445, 151700, 157222, 161583, 164020, 199231, 105098, 155044, 155456, 112223, 187271, 181250, 194188, 160804, 178931, 105931, 165406, 125303, 114540, 125239, 130999, 120994, 180067, 123707, 118916, 176169, 109430, 137241, 163375, 164043, 115371, 116089, 173161, 124787, 168174, 106895, 199195, 109821, 129316, 182071, 114228, 147744, 103268, 157744, 111583, 143429, 133417, 165520, 191097, 118066, 131212, 188190, 197151, 161389, 142503, 112709, 120636, 188371, 198426, 153760, 159488, 173271, 184459, 168881, 139562, 195116, 141426, 172021, 158039, 187178, 167222, 136739, 191517, 140811, 197482, 147531, 194197, 159243, 105361, 156336, 103873, 108784, 184822, 148771, 142591, 143986, 102092, 117106, 130570, 141623, 187361, 107163, 188128, 140183, 108299, 190484, 156424, 177552, 108415, 114474, 188499, 118804, 105207, 163526, 120197, 100539, 169603, 112218, 132070, 149528, 175009, 168079, 150084, 114110, 115989, 109285, 106034, 166083, 119561, 170070, 189330, 163622, 189311, 191673, 111312, 117065, 109208, 187637, 106358, 115169, 143409, 154500, 139582, 131700, 119256, 113392, 163498, 148017, 175448, 125008, 170681, 181230, 115054, 150202, 135926, 199605, 180858, 120045, 116807, 168380, 113695, 180686, 129878, 135642, 164632, 160505, 196411, 149643, 155561, 108873, 145688, 137406, 132856, 162599, 172439, 109613, 152771, 158470, 172232, 101194, 137085, 143622, 192003, 123252, 184080, 114911, 102566, 123777, 100350, 125553, 114712, 172475, 147456, 188194, 155290, 185811, 105017, 192984, 125448, 183887, 186176, 197144, 151111, 108729, 144038, 112686, 188119, 184394, 165472, 119530, 110033, 166548, 197791, 190624, 139712, 168911, 180051, 121318, 176123, 175933, 125325, 121758, 134344, 115247, 118636, 123804, 134471, 195030, 112886, 151010, 138977, 185191, 159374, 107543, 183858, 119492, 125013, 135644, 108588, 149638, 160748, 141494, 159033, 110587, 122513, 181181, 171527, 129078, 150877, 174921, 118720, 194788, 161783, 149549, 189935, 180321, 124522, 136210, 138523, 194370, 152254, 162023, 177794, 172104, 188451, 110549, 172278, 139796, 133081, 106252, 150959, 114044, 164556, 101732, 195302, 121591, 127631]
357

In [52]:
HADMgroup = Input3.groupby(['HADM_ID'])

In [53]:
ID_ITEM= {}
for i in H_ID:
    d = HADMgroup.get_group(i)
    d1 = d['ITEMID'].value_counts().rename_axis('unique_itemID').reset_index(name='count')
    list = d1['unique_itemID'].tolist()
    print("ITEM_ID for HADM_ID:" ,+i)
    print(list)
    ID_ITEM["%s" %i] = list

ITEM_ID for HADM_ID: 172260
[30013, 30131, 30051, 30047, 30043, 30140, 30032, 30018, 30063, 30144, 30095, 30008, 30005, 30001]
ITEM_ID for HADM_ID: 146995
[30018, 30013, 30056]
ITEM_ID for HADM_ID: 193149
[30018, 30056]
ITEM_ID for HADM_ID: 179287
[30056, 30013]
ITEM_ID for HADM_ID: 103904
[30013, 30077, 30025, 30066, 30001, 30056]
ITEM_ID for HADM_ID: 114345
[30045, 30013, 30018, 30115, 30032, 30005, 30001, 30030, 30054]
ITEM_ID for HADM_ID: 148158
[30013, 30018, 30056, 30026]
ITEM_ID for HADM_ID: 185483
[30164, 30095, 30144]
ITEM_ID for HADM_ID: 103195
[30013]
ITEM_ID for HADM_ID: 101184
[30018, 30056]
ITEM_ID for HADM_ID: 183920
[30060, 30056, 30018, 30013]
ITEM_ID for HADM_ID: 151003
[30056, 30018]
ITEM_ID for HADM_ID: 155281
[30056]
ITEM_ID for HADM_ID: 150778
[30126, 30018, 30013, 30056, 30095, 30030, 30077, 30144]
ITEM_ID for HADM_ID: 122293
[30015, 30057, 30013, 30001, 30077, 30095]
ITEM_ID for HADM_ID: 103778
[30015, 30096, 30013, 30026, 30056]
ITEM_ID for HADM_ID: 158408
[30013, 30045, 30163, 30141, 30114, 30018, 30120, 30073, 30123, 30095, 30026]
ITEM_ID for HADM_ID: 149043
[30018, 30045, 30166, 30126, 30013, 30144, 30095, 30099, 30006]
ITEM_ID for HADM_ID: 112560
[30018, 30013, 30056, 30128]
ITEM_ID for HADM_ID: 184219
[30018, 30026, 30056]
ITEM_ID for HADM_ID: 118985
[30025, 30013, 30018, 30015, 30056]
ITEM_ID for HADM_ID: 147012
[30042, 30131, 30018, 30120, 30013, 30140, 30045, 30096, 30141, 30118, 30001]
ITEM_ID for HADM_ID: 138331
[30018, 30089, 30078, 30144, 30095, 30001, 30013]
ITEM_ID for HADM_ID: 185100
[30015]
ITEM_ID for HADM_ID: 181158
[30073, 30056, 30144]
ITEM_ID for HADM_ID: 129493
[30018, 30354, 30144, 30013, 30056, 30095, 30001]
ITEM_ID for HADM_ID: 188196
[30018, 30013, 30124, 30118, 30051, 30045, 30025, 30120, 30042, 30021, 30166, 30128, 42940, 30095, 30144, 30054]
ITEM_ID for HADM_ID: 168094
[30128, 30013, 30018, 30021, 30056, 30029]
ITEM_ID for HADM_ID: 144017
[30018]
ITEM_ID for HADM_ID: 123912
[30013]
ITEM_ID for HADM_ID: 177199
[30013, 30056]
ITEM_ID for HADM_ID: 161064
[30021, 30013, 30056, 30018]
ITEM_ID for HADM_ID: 189199
[30018, 30032, 30013, 30056, 30001, 30120]
ITEM_ID for HADM_ID: 166956
[30018, 30056, 30013, 30026]
ITEM_ID for HADM_ID: 137772
[30018, 30124, 30118, 30112, 30128, 30013, 30164, 30144, 30095, 30006]
ITEM_ID for HADM_ID: 158183
[30025, 30018, 30013, 30045, 30124, 30118, 30166, 30059, 30144, 30095]
ITEM_ID for HADM_ID: 175586
[30013, 30120, 30051, 30112, 30018, 30164, 30118, 30025, 30144, 30059, 30095, 30026]
ITEM_ID for HADM_ID: 194424
[30018, 30124, 30120, 30118, 30043, 30013, 30051, 30095, 30144]
ITEM_ID for HADM_ID: 148295
[30013, 30051, 30043, 30018, 30126, 30164, 30023, 30095, 30026, 30144, 30001]
ITEM_ID for HADM_ID: 179519
[30018, 30118, 30123, 30045, 30124, 30354, 30013, 30029, 30058, 30144, 30095, 30059]
ITEM_ID for HADM_ID: 193274
[30165, 30089, 30018, 30177, 30013, 30144, 30058]
ITEM_ID for HADM_ID: 114997
[30013, 30120, 30051, 30018, 30128, 30131, 30045, 30023, 30140, 30030, 30005, 30077, 30056, 30021, 30054, 30015, 30126]
ITEM_ID for HADM_ID: 186968
[30018, 30013, 30056]
ITEM_ID for HADM_ID: 186821
[30018, 30056, 30013]
ITEM_ID for HADM_ID: 182589
[30018, 30013]
ITEM_ID for HADM_ID: 185758
[30018, 30056]
ITEM_ID for HADM_ID: 116181
[30013, 30025, 30131, 30018, 30032, 30128, 30140, 30120, 30030, 30126, 30056, 30054, 30006, 30005, 30001]
ITEM_ID for HADM_ID: 156972
[30126, 30018, 30013, 30056, 30120]
ITEM_ID for HADM_ID: 111109
[30056]
ITEM_ID for HADM_ID: 169217
[30018, 30056, 30013, 30140, 30131, 30120, 30030, 30025]
ITEM_ID for HADM_ID: 122915
[30013, 30056, 30026]
ITEM_ID for HADM_ID: 104329
[30013, 30121, 30018, 30056, 30144, 30054, 30001]
ITEM_ID for HADM_ID: 115662
[30013, 30018, 30120, 30126, 30124, 30118, 30144, 30001]
ITEM_ID for HADM_ID: 188392
[30128, 30013, 30120, 30051, 30096, 30118, 30119, 30018, 44425, 30114, 30001, 30005, 30021, 30007, 30006, 30056]
ITEM_ID for HADM_ID: 169557
[30013]
ITEM_ID for HADM_ID: 122982
[30018, 30166, 30073, 30013, 30026, 30144, 30095]
ITEM_ID for HADM_ID: 123040
[30013]
ITEM_ID for HADM_ID: 151652
[30018, 30013, 30056]
ITEM_ID for HADM_ID: 170984
[30126, 30018, 30013]
ITEM_ID for HADM_ID: 190582
[30056]
ITEM_ID for HADM_ID: 107286
[30056, 30013, 30029, 30120, 30018]
ITEM_ID for HADM_ID: 148365
[30018, 30166, 30045, 30013, 30058, 30144, 30056, 30140, 30131, 30120]
ITEM_ID for HADM_ID: 102847
[30124, 30118, 30018, 30057, 30131, 30095, 30140, 30013, 30144, 44938, 30101, 30025]
ITEM_ID for HADM_ID: 173681
[30128, 30018, 30013, 30166, 30025, 30120, 30131, 45104, 30144, 30001, 30095, 30126, 30102, 30056, 30009]
ITEM_ID for HADM_ID: 111970
[30126, 30013, 30018, 30051, 30096, 30120, 30001, 30144, 30015, 30005]
ITEM_ID for HADM_ID: 149844
[30013, 30056]
ITEM_ID for HADM_ID: 135251
[30056, 30018]
ITEM_ID for HADM_ID: 156400
[30120, 30013, 30018, 30043, 30056, 30054]
ITEM_ID for HADM_ID: 171681
[30077, 30018, 30058, 30056, 30144, 30013, 30095, 30001]
ITEM_ID for HADM_ID: 189051
[30013, 30128, 30120, 30018, 30144, 30005, 30056, 30006]
ITEM_ID for HADM_ID: 162875
[30015, 30056]
ITEM_ID for HADM_ID: 160080
[30013, 30026, 30018, 30056, 30015]
ITEM_ID for HADM_ID: 147319
[30018, 30056, 30013]
ITEM_ID for HADM_ID: 153858
[30120, 30013, 30018, 30045, 30077, 30144, 30095, 41642, 30021]
ITEM_ID for HADM_ID: 171106
[30077, 30018, 30013, 30144, 30059, 30001, 30095]
ITEM_ID for HADM_ID: 150506
[30056, 30018]
ITEM_ID for HADM_ID: 121097
[30018, 30056, 30013, 30059, 30058, 30166, 30095, 30144]
ITEM_ID for HADM_ID: 170106
[30018, 30056, 30026, 30013]
ITEM_ID for HADM_ID: 147119
[30126, 30013, 30018, 30120, 30051]
ITEM_ID for HADM_ID: 175912
[30018, 30013, 30077, 30144, 30095]
ITEM_ID for HADM_ID: 151808
[30126, 30018, 30013, 30056]
ITEM_ID for HADM_ID: 189131
[30056]
ITEM_ID for HADM_ID: 104141
[30001, 30013, 30056]
ITEM_ID for HADM_ID: 105557
[30018]
ITEM_ID for HADM_ID: 154361
[30021, 30013, 30120, 30056, 30001]
ITEM_ID for HADM_ID: 146426
[30090, 30018, 30058, 30144, 30013, 30095, 30026]
ITEM_ID for HADM_ID: 159459
[30018, 30056]
ITEM_ID for HADM_ID: 195303
[30056, 30018]
ITEM_ID for HADM_ID: 134462
[30018, 30013, 30056]
ITEM_ID for HADM_ID: 146738
[30120, 30018, 30013, 30124, 30118, 30030, 30026, 30023, 30051, 30069, 30068, 30028, 30065, 30126, 30005, 30144, 30001, 30021, 30056]
ITEM_ID for HADM_ID: 108445
[30018, 30013, 30021]
ITEM_ID for HADM_ID: 151700
[30013, 30354, 30144]
ITEM_ID for HADM_ID: 157222
[30018, 30090, 30144, 30013, 30059, 30095, 30026]
ITEM_ID for HADM_ID: 161583
[30013, 30018]
ITEM_ID for HADM_ID: 164020
[30025, 30018, 30124, 30013, 30118, 30078, 30131, 30140, 30128, 30144, 30095, 30059, 30058, 30056, 30026, 30001]
ITEM_ID for HADM_ID: 199231
[30018]
ITEM_ID for HADM_ID: 105098
[30013, 30018, 30120, 30030]
ITEM_ID for HADM_ID: 155044
[30118, 30018, 30126, 30013, 30032, 30168, 30124, 30045, 30009]
ITEM_ID for HADM_ID: 155456
[30018, 30029, 30056, 30013]
ITEM_ID for HADM_ID: 112223
[30018, 30056, 30013]
ITEM_ID for HADM_ID: 187271
[30056]
ITEM_ID for HADM_ID: 181250
[30021, 30018, 30128, 30131, 30401, 46174, 30029, 30013, 30001, 30140, 30144, 30005, 30026, 30008]
ITEM_ID for HADM_ID: 194188
[30018, 30056]
ITEM_ID for HADM_ID: 160804
[30013, 30056]
ITEM_ID for HADM_ID: 178931
[30018, 30088, 30144, 30013, 30058, 30095]
ITEM_ID for HADM_ID: 105931
[30018, 30120, 30013, 30029, 30056]
ITEM_ID for HADM_ID: 165406
[30018, 30013, 30124, 30118, 30095, 30059, 30144, 30354, 30001]
ITEM_ID for HADM_ID: 125303
[30025, 30013, 30026, 30023, 30018, 30126, 30404, 30058]
ITEM_ID for HADM_ID: 114540
[30013, 30126, 30115, 30403, 30018, 30144, 30058, 30056]
ITEM_ID for HADM_ID: 125239
[30013, 30018, 30120, 30051, 30124, 30118, 30043, 30128, 30112, 30030, 30126, 30056]
ITEM_ID for HADM_ID: 130999
[30018, 30354, 30058, 30013, 30144, 30095, 30030, 30015, 30009]
ITEM_ID for HADM_ID: 120994
[225158, 220949, 221749, 221662, 225893, 225828, 221668, 222315, 221744, 220862, 225944, 225875, 220995, 222011, 221456, 225798]
ITEM_ID for HADM_ID: 180067
[30115, 30013, 30026, 30015, 30018, 30056]
ITEM_ID for HADM_ID: 123707
[30021, 30056, 30013, 30120]
ITEM_ID for HADM_ID: 118916
[30018, 30056]
ITEM_ID for HADM_ID: 176169
[30018, 30013, 30056, 30015, 30026]
ITEM_ID for HADM_ID: 109430
[30018, 30056, 30013]
ITEM_ID for HADM_ID: 137241
[30018, 30120, 30056, 30013, 30095, 30059, 30058, 30144]
ITEM_ID for HADM_ID: 163375
[30018, 30025, 30013, 30128, 30354, 30059, 30144]
ITEM_ID for HADM_ID: 164043
[30403, 30018, 30095, 30144, 30059, 30013]
ITEM_ID for HADM_ID: 115371
[30025, 30403, 30018, 30013, 30144, 30059, 30056, 30058, 30095]
ITEM_ID for HADM_ID: 116089
[30018, 30013, 30117, 30056]
ITEM_ID for HADM_ID: 173161
[30018, 30013, 30058]
ITEM_ID for HADM_ID: 124787
[30013, 30018, 30043, 30163, 30141, 30128, 30023, 42440, 30120, 30032, 30030, 30005, 30095, 30001, 30026, 30009, 30077, 30007, 30006]
ITEM_ID for HADM_ID: 168174
[30013, 30120, 30051, 30128, 30018, 30118, 30030]
ITEM_ID for HADM_ID: 106895
[30164, 30018, 30013, 30144, 30095, 30001]
ITEM_ID for HADM_ID: 199195
[30018, 30086, 30144, 30095, 30013, 30001]
ITEM_ID for HADM_ID: 109821
[30025, 30043, 30013, 30123, 30018, 30128, 30089, 30078, 30112, 30001, 30126]
ITEM_ID for HADM_ID: 129316
[30166, 30015, 30018, 30013, 30095, 30144]
ITEM_ID for HADM_ID: 182071
[30032, 30013, 30026]
ITEM_ID for HADM_ID: 114228
[30013, 30141, 30118, 30018, 30164, 30120, 30043, 30126, 30144, 30095, 30054]
ITEM_ID for HADM_ID: 147744
[30032, 30018, 30118, 30144, 30141, 30095, 30164, 30013]
ITEM_ID for HADM_ID: 103268
[30124, 30118, 30018, 30032, 30077, 30013, 30095, 30001, 30144, 30058, 30006]
ITEM_ID for HADM_ID: 157744
[30018, 30077, 30013, 30144, 30059, 30095, 30001]
ITEM_ID for HADM_ID: 111583
[30013, 30118, 30120, 30112, 30124, 30018, 30006]
ITEM_ID for HADM_ID: 143429
[30013, 30141, 30118, 30047, 30018, 30113, 30030, 30077, 30095, 30144, 30127, 30005]
ITEM_ID for HADM_ID: 133417
[30018, 30015, 30020, 30026, 30013, 30166, 30054, 30144, 30001]
ITEM_ID for HADM_ID: 165520
[30013, 30126, 30128, 30025, 30018, 30051]
ITEM_ID for HADM_ID: 191097
[30013, 30163, 30112, 30141, 30047, 30128, 30043, 30114, 30032, 30115, 30096, 42387, 30009, 30005]
ITEM_ID for HADM_ID: 118066
[30018, 30118, 30045, 30124, 30165, 30095, 30144, 30013, 30059, 30001]
ITEM_ID for HADM_ID: 131212
[30013, 30126, 30120, 30051, 30018, 30144]
ITEM_ID for HADM_ID: 188190
[30166, 30018, 30013, 30058, 30144, 30095, 30001]
ITEM_ID for HADM_ID: 197151
[30018, 30045, 30126, 30077, 30118, 30013, 30095]
ITEM_ID for HADM_ID: 161389
[30120, 30051, 30045, 30018, 30013, 30119, 30005, 30001, 30046, 30021, 30104, 30030]
ITEM_ID for HADM_ID: 142503
[30032, 30018, 30013]
ITEM_ID for HADM_ID: 112709
[30120, 30051, 30013, 30018, 30144, 30005, 30126, 30054]
ITEM_ID for HADM_ID: 120636
[30013, 30149, 30045, 30120, 30150, 30073, 30018, 30058, 30126, 30026, 30144, 30001]
ITEM_ID for HADM_ID: 188371
[30120, 30013, 30126, 30018, 30043, 30021]
ITEM_ID for HADM_ID: 198426
[30018, 30166, 30126, 30013, 30095, 30144, 30059, 30128]
ITEM_ID for HADM_ID: 153760
[30166, 30018, 30013, 30144, 30095, 30058, 30001]
ITEM_ID for HADM_ID: 159488
[30018, 30144, 30013, 30077]
ITEM_ID for HADM_ID: 173271
[30018, 30118, 30078, 30013, 30123, 30001, 30095]
ITEM_ID for HADM_ID: 184459
[30120, 30051, 30013, 30018, 30144]
ITEM_ID for HADM_ID: 168881
[30078, 30018, 30144]
ITEM_ID for HADM_ID: 139562
[30165, 30018, 30058, 30144, 30013, 30354, 30095, 30001]
ITEM_ID for HADM_ID: 195116
[30018, 30166, 30013]
ITEM_ID for HADM_ID: 141426
[30051, 30013, 30018, 30120, 30124, 30118, 30077, 30095, 30144, 30005, 30030, 30023, 30001]
ITEM_ID for HADM_ID: 172021
[30018, 30071, 30013, 30051, 30045, 30095, 30058, 30354, 30144, 30059, 30054, 30030]
ITEM_ID for HADM_ID: 158039
[30018, 30354, 30028, 30013, 30058, 30095, 30144, 30059]
ITEM_ID for HADM_ID: 187178
[30126, 30018, 30013, 30124, 30123, 30118]
ITEM_ID for HADM_ID: 167222
[30018, 30124, 30118, 30045, 30078, 30013, 30058, 30095, 30144, 30120, 30026]
ITEM_ID for HADM_ID: 136739
[30013, 30128, 30123, 30120, 30118, 30114, 30025, 30078, 30018, 30051, 30144, 30023, 30131, 30095, 30026, 30009, 30140]
ITEM_ID for HADM_ID: 191517
[30018, 30120]
ITEM_ID for HADM_ID: 140811
[30165, 30018, 30144, 30013, 30095, 30059, 30354]
ITEM_ID for HADM_ID: 197482
[30086, 30018, 30013, 30058, 30144, 30095]
ITEM_ID for HADM_ID: 147531
[30018, 30090, 30058, 30013, 30144]
ITEM_ID for HADM_ID: 194197
[30013, 30383, 30144, 30058, 30077, 30095, 30025, 30005]
ITEM_ID for HADM_ID: 159243
[30015, 30013, 30018]
ITEM_ID for HADM_ID: 105361
[30120, 30013, 30018, 30126, 30030, 30144, 30054, 30059]
ITEM_ID for HADM_ID: 156336
[30020, 30354, 30013, 30058, 30095, 30144, 30025, 30001]
ITEM_ID for HADM_ID: 103873
[30120, 30013, 30018, 30066, 30021, 30015]
ITEM_ID for HADM_ID: 108784
[30354, 30018, 30013, 30144, 30058, 30095]
ITEM_ID for HADM_ID: 184822
[30128, 30124, 30118, 30013, 30018, 30025]
ITEM_ID for HADM_ID: 148771
[30018, 30118, 30124, 30120, 30013, 30128, 30051, 30030, 30144, 30095, 30059, 30077]
ITEM_ID for HADM_ID: 142591
[30090, 30018, 30144, 30059, 30013, 30095]
ITEM_ID for HADM_ID: 143986
[30018, 30354, 30058, 30013, 30144, 30095]
ITEM_ID for HADM_ID: 102092
[30071, 30018, 30013, 30059, 30144, 30095]
ITEM_ID for HADM_ID: 117106
[30126, 30018, 30013, 30354, 30095, 30144]
ITEM_ID for HADM_ID: 130570
[30073, 30018, 30013, 30058, 30026]
ITEM_ID for HADM_ID: 141623
[30018, 30013, 30354, 30058, 30059, 30045, 30144, 30128]
ITEM_ID for HADM_ID: 187361
[30013]
ITEM_ID for HADM_ID: 107163
[30013, 30018, 30124, 30120, 30118, 30051, 30133, 30126, 30008, 30144, 30095, 30090, 30026, 30005]
ITEM_ID for HADM_ID: 188128
[30018, 30090, 30058, 30144, 30059, 30013]
ITEM_ID for HADM_ID: 140183
[30404, 30089, 30018, 30058, 30144, 30059, 30013]
ITEM_ID for HADM_ID: 108299
[30018, 30354, 30058, 30013, 30029, 30144]
ITEM_ID for HADM_ID: 190484
[30018, 30013, 30128, 30001, 30144]
ITEM_ID for HADM_ID: 156424
[30018, 30013, 30029]
ITEM_ID for HADM_ID: 177552
[30128, 30013, 30018, 30404, 30123, 30059, 30095, 30144]
ITEM_ID for HADM_ID: 108415
[30013, 30128]
ITEM_ID for HADM_ID: 114474
[30018]
ITEM_ID for HADM_ID: 188499
[30128, 30013, 30018, 30030, 30115, 30021, 30126, 30008, 46181, 30100, 30066, 30032, 30026]
ITEM_ID for HADM_ID: 118804
[30018, 30013, 30120, 30045, 30020, 30126, 30030]
ITEM_ID for HADM_ID: 105207
[30404, 30060]
ITEM_ID for HADM_ID: 163526
[30078, 30018, 30144, 30026, 30015, 30005, 30001]
ITEM_ID for HADM_ID: 120197
[30354, 30066, 30021, 30018, 30144, 30095]
ITEM_ID for HADM_ID: 100539
[30032]
ITEM_ID for HADM_ID: 169603
[30120, 30018, 30166, 30058, 30043, 30059, 30001]
ITEM_ID for HADM_ID: 112218
[30073, 30144]
ITEM_ID for HADM_ID: 132070
[30128, 30045, 30013, 30173, 30018, 30023, 30043, 30126]
ITEM_ID for HADM_ID: 149528
[30126, 30026, 30018, 30013]
ITEM_ID for HADM_ID: 175009
[30018, 30118, 30013]
ITEM_ID for HADM_ID: 168079
[30013, 30125, 30120, 30119, 30051, 30045, 30018, 30126]
ITEM_ID for HADM_ID: 150084
[30018, 30173, 30026, 30023, 30013, 30045, 30006]
ITEM_ID for HADM_ID: 114110
[30018]
ITEM_ID for HADM_ID: 115989
[30368]
ITEM_ID for HADM_ID: 109285
[226452, 221385, 221833, 225158, 223258, 220949, 225884, 225893, 225892]
ITEM_ID for HADM_ID: 106034
[225883, 220949, 226452, 225943, 225910]
ITEM_ID for HADM_ID: 166083
[226452, 225158, 220949, 225851, 225855, 222011, 225975, 225798, 221794]
ITEM_ID for HADM_ID: 119561
[225158, 220949, 221668, 221555, 225943, 225944, 225942, 221744, 221906, 225152, 225883, 221749, 225168, 226089, 225881, 225828, 222315, 225848, 222011, 225884, 225166, 225170, 221456]
ITEM_ID for HADM_ID: 170070
[226452, 225158, 225851, 220949, 225975, 225907, 221744, 221668, 222011]
ITEM_ID for HADM_ID: 189330
[225158, 221794, 225154, 225152, 220949, 225168, 225893, 220952]
ITEM_ID for HADM_ID: 163622
[225158, 221749, 225154, 220949, 222315, 225893, 223262, 225798, 225907, 225943, 221456]
ITEM_ID for HADM_ID: 189311
[226452, 220949, 225853, 225975, 225158, 222011, 225944, 225859]
ITEM_ID for HADM_ID: 191673
[225158, 225166, 225944, 221749, 220949, 223258, 221906, 221456, 227528, 227526, 225799, 225884, 225947, 225883, 220952, 225798, 225916, 225869, 221744, 225833, 220950, 221668, 220995, 225834, 223262, 225917, 225168, 226453, 225948, 220864]
ITEM_ID for HADM_ID: 111312
[225158, 220949, 225798, 225930, 225893]
ITEM_ID for HADM_ID: 117065
[226452, 225893, 220949, 225158]
ITEM_ID for HADM_ID: 109208
[225929, 225799, 225158, 225797, 225975, 225834, 225910, 225943, 226453, 221794]
ITEM_ID for HADM_ID: 187637
[225975, 225158]
ITEM_ID for HADM_ID: 106358
[225158]
ITEM_ID for HADM_ID: 115169
[226452]
ITEM_ID for HADM_ID: 143409
[220949, 225154, 225892, 226453, 221824, 225798, 225936, 225799, 221794, 222168, 225943, 225158, 221744, 221668]
ITEM_ID for HADM_ID: 154500
[220949, 226880, 225797, 225893, 225158, 225799, 225828, 225975, 223258, 225943, 225798, 225910, 221794, 223260, 225944, 226089, 225168, 225166, 222011]
ITEM_ID for HADM_ID: 139582
[220949, 225154, 221744, 225799, 223258, 221036, 225970, 223259, 225797, 221668, 225158, 225907, 227531, 225975]
ITEM_ID for HADM_ID: 131700
[225158, 225893, 220949, 220952, 226452, 221794]
ITEM_ID for HADM_ID: 119256
[225158]
ITEM_ID for HADM_ID: 113392
[225166, 225823, 226050, 226089, 220949, 225893, 225974, 223258, 226452, 222011, 225975, 225910, 225834, 225943, 225798]
ITEM_ID for HADM_ID: 163498
[225158, 220949, 220995, 223258, 222315, 225860, 221456, 225865, 225154, 221906, 225853, 225910, 225943, 225170, 225168, 225798, 225825, 222011, 227523, 220970]
ITEM_ID for HADM_ID: 148017
[220949, 226453, 225799, 225798, 225884, 225931, 225797, 225910, 225943, 225158, 225975, 223262, 225154, 223260]
ITEM_ID for HADM_ID: 175448
[220949, 225154, 225970, 226880, 225909, 225799, 225975]
ITEM_ID for HADM_ID: 125008
[225943, 222168, 225158, 221906, 220949, 225892, 225884, 225910, 221744, 225798, 225859, 223258, 225154]
ITEM_ID for HADM_ID: 170681
[220949, 225152, 225893, 225158, 226452]
ITEM_ID for HADM_ID: 181230
[225975, 225158, 225797, 225936]
ITEM_ID for HADM_ID: 115054
[221744, 220949, 225154, 225943, 222168, 225893, 225158, 221036, 225970, 225975, 225910, 225884, 222011, 225974, 226089, 225799]
ITEM_ID for HADM_ID: 150202
[225944, 222011, 226452]
ITEM_ID for HADM_ID: 135926
[226452, 225975, 222011, 225910, 227523]
ITEM_ID for HADM_ID: 199605
[225158, 220949, 220862, 221833, 225944, 225799, 227526, 227529, 227536, 221906, 221347, 227525, 225934, 225154, 225883, 225943, 225910, 221749, 223258, 223260, 221456, 221668, 225916, 226453, 226089, 222011, 225797]
ITEM_ID for HADM_ID: 180858
[225158, 223258]
ITEM_ID for HADM_ID: 120045
[225158, 221906]
ITEM_ID for HADM_ID: 116807
[225158, 221744, 225166, 225154, 225823, 220949, 221906, 225828, 220952, 222315, 225883, 225798, 225910, 225975, 225943, 221456]
ITEM_ID for HADM_ID: 168380
[220949, 226452, 223262, 223260, 225893, 225158, 225154, 225892]
ITEM_ID for HADM_ID: 113695
[225158, 221749, 225970, 225931, 220949, 225798, 225893, 225154, 223259, 223262, 226453, 225799]
ITEM_ID for HADM_ID: 180686
[225158, 225931, 221906]
ITEM_ID for HADM_ID: 129878
[226452, 225158, 220949, 225842]
ITEM_ID for HADM_ID: 135642
[226452, 225975, 220949, 225158, 225798, 225902, 225892]
ITEM_ID for HADM_ID: 164632
[225158]
ITEM_ID for HADM_ID: 160505
[226453, 227975, 220949, 225799, 225158, 223262, 222315, 221744]
ITEM_ID for HADM_ID: 196411
[226452, 225834, 225158]
ITEM_ID for HADM_ID: 149643
[220949, 225158, 225798, 225975, 225855, 226452, 221744]
ITEM_ID for HADM_ID: 155561
[225158, 227695, 220949, 226452, 225893]
ITEM_ID for HADM_ID: 108873
[226452, 225975, 223262, 222011, 225158, 227523, 225909, 227694, 221794]
ITEM_ID for HADM_ID: 145688
[225158, 221906]
ITEM_ID for HADM_ID: 137406
[225158, 220949, 221906, 221749, 221668, 225799, 221744, 225975, 225152, 225881, 226453, 221456, 225875, 225883, 220995, 223262, 225944, 225910]
ITEM_ID for HADM_ID: 132856

In [54]:
counter_c = []
counter1_c = []
for v in ID_ITEM.values():
    counter_c.append(v)
for i in counter_c:
    for j in i:
        counter1_c.append(j)
        
from collections import Counter
a1 = Counter(counter1_c)
Common_c = a1.most_common(15)
Common_c

[(30013, 170),
 (30018, 169),
 (225158, 131),
 (220949, 105),
 (30144, 89),
 (30056, 73),
 (30095, 66),
 (225975, 56),
 (226452, 54),
 (30120, 48),
 (225798, 47),
 (225943, 45),
 (225154, 45),
 (225799, 43),
 (30001, 42)]

In [55]:
Common = [item[0] for item in Common_c]
print(Common)

[30013, 30018, 225158, 220949, 30144, 30056, 30095, 225975, 226452, 30120, 225798, 225943, 225154, 225799, 30001]

In [56]:
Common = ['.9% Normal Saline','NaCl 0.9%','PO Intake','Po Intake','D5W','Dextrose 5%','Levophed-k','Norepinephrine']

In [57]:
Input3 = Input3[Input3['LABEL'].isin(Common)]

In [58]:
Input3['LABEL'].unique()

array(['D5W', '.9% Normal Saline', 'Po Intake', 'Levophed-k', 'NaCl 0.9%',
       'Dextrose 5%', 'PO Intake', 'Norepinephrine'], dtype=object)

In [59]:
Input3['LABEL'].value_counts()

.9% Normal Saline    6795
D5W                  5390
Levophed-k           2376
NaCl 0.9%            1262
Dextrose 5%          1002
Norepinephrine        423
Po Intake             272
PO Intake             225
Name: LABEL, dtype: int64

In [60]:
Input3['LABEL'] = Input3['LABEL'].replace({'.9% Normal Saline':'NaCl 0.9%'})
Input3['LABEL'] = Input3['LABEL'].replace({'PO Intake':'Po Intake'})
Input3['LABEL'] = Input3['LABEL'].replace({'D5W':'Dextrose 5%'})
Input3['LABEL'] = Input3['LABEL'].replace({'Levophed-k':'Norepinephrine'})

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [61]:
Input3['AMOUNTUOM'].unique()

array(['ml', nan, 'mg'], dtype=object)

In [62]:
Input3["LABEL"] = Input3["LABEL"].str.upper()

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [63]:
Input3.isna().sum()

SUBJECT_ID           0
HADM_ID              0
ENDTIME              0
ITEMID               0
AMOUNT            1639
AMOUNTUOM         1675
RATE             14157
RATEUOM          14144
PATIENTWEIGHT    14833
LABEL                0
ADMITTIME            0
DISCHTIME            0
dtype: int64

In [64]:
Input3.reset_index(inplace=True)
Input3 = Input3.rename(columns = {'index':'INDEX'})

In [65]:
nick = Input3.pivot(columns='LABEL',values='AMOUNT', index='INDEX')

In [66]:
nick = nick.rename(columns = {'index':'INDEX'})

In [67]:
Input4 = pd.merge(Input3, nick, on=['INDEX'])
Input4.head()

,INDEX,SUBJECT_ID,HADM_ID,ENDTIME,ITEMID,AMOUNT,AMOUNTUOM,RATE,RATEUOM,PATIENTWEIGHT,LABEL,ADMITTIME,DISCHTIME,DEXTROSE 5%,NACL 0.9%,NOREPINEPHRINE,PO INTAKE
0,4355,590,172260,2124-11-15 09:00:00,30013,100.0,ml,NaN,NaN,NaN,DEXTROSE 5%,2124-11-02 08:56:00,2124-11-15 18:29:00,100.0,NaN,NaN,NaN
1,4356,590,172260,2124-11-15 10:00:00,30013,50.0,ml,NaN,NaN,NaN,DEXTROSE 5%,2124-11-02 08:56:00,2124-11-15 18:29:00,50.0,NaN,NaN,NaN
2,4357,590,172260,2124-11-15 14:00:00,30013,100.0,ml,NaN,NaN,NaN,DEXTROSE 5%,2124-11-02 08:56:00,2124-11-15 18:29:00,100.0,NaN,NaN,NaN
3,4476,590,172260,2124-11-14 23:00:00,30013,35.0,ml,NaN,NaN,NaN,DEXTROSE 5%,2124-11-02 08:56:00,2124-11-15 18:29:00,35.0,NaN,NaN,NaN
4,4477,590,172260,2124-11-15 01:30:00,30013,87.5,ml,NaN,NaN,NaN,DEXTROSE 5%,2124-11-02 08:56:00,2124-11-15 18:29:00,87.5,NaN,NaN,NaN

In [68]:
Input4.shape

(17745, 17)

In [69]:
Input4.columns

Index(['INDEX', 'SUBJECT_ID', 'HADM_ID', 'ENDTIME', 'ITEMID', 'AMOUNT',
       'AMOUNTUOM', 'RATE', 'RATEUOM', 'PATIENTWEIGHT', 'LABEL', 'ADMITTIME',
       'DISCHTIME', 'DEXTROSE 5%', 'NACL 0.9%', 'NOREPINEPHRINE', 'PO INTAKE'],
      dtype='object')

In [70]:
Input4.drop(['INDEX', 'ENDTIME', 'ITEMID', 'AMOUNT',
       'AMOUNTUOM', 'RATE', 'RATEUOM', 'LABEL','PATIENTWEIGHT', 'ADMITTIME','DISCHTIME','SUBJECT_ID',
             ], axis=1, inplace = True)

In [71]:
print(len(Input4['HADM_ID'].unique()))

348

In [72]:
Input4[Input4 < 0] = np.NaN

In [73]:
Input4.columns

Index(['HADM_ID', 'DEXTROSE 5%', 'NACL 0.9%', 'NOREPINEPHRINE', 'PO INTAKE'], dtype='object')

In [74]:
Input4['HADM_ID'] = Input4['HADM_ID'].astype(str)

In [75]:
v = Input4['HADM_ID'].unique()

In [76]:
Input4.describe()

       DEXTROSE 5%    NACL 0.9%  NOREPINEPHRINE    PO INTAKE
count  6322.000000  7965.000000     1317.000000   495.000000
mean     67.874263    44.726121        1.506402   182.010101
std     136.016219   135.784064        2.510787   136.853559
min       0.000000     0.000000        0.000000     0.000000
25%       6.121875     5.000000        0.303840   100.000000
50%      25.000000    10.000000        0.692400   150.000000
75%     100.000000    19.243502        1.472000   240.000000
max    3000.000000  1946.250079       32.332801  1500.000000

In [77]:
grouped = Input4.groupby('HADM_ID')

In [78]:
Input4.isna().sum()

HADM_ID               0
DEXTROSE 5%       11423
NACL 0.9%          9780
NOREPINEPHRINE    16428
PO INTAKE         17250
dtype: int64

In [79]:
# Removing the outliers
def removeOutliers(f):
    filt_df = f.loc[:, f.columns != 'HADM_ID']
    low = .1
    high = .9
    quant_df = filt_df.quantile([low, high])
    
    print(quant_df)
     
    filt_df = filt_df.apply(lambda x: x[(x>quant_df.loc[low,x.name]) &
                                    (x < quant_df.loc[high,x.name])], axis=0)
        
    filt_df = pd.concat([f.loc[:,'HADM_ID'], filt_df], axis=1)
    print(filt_df.shape)
    return filt_df

In [80]:
ck = []
for k in v:
    f = grouped.get_group(k)
    print("HADM_ID %s" %k)
    ck.append(removeOutliers(f))

HADM_ID 172260
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1       6.9000       10.0             NaN        NaN
0.9      49.6875       20.0             NaN        NaN
(135, 5)
HADM_ID 146995
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        120.0      300.0             NaN      240.0
0.9        120.0      635.0             NaN      240.0
(6, 5)
HADM_ID 193149
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN        5.0             NaN      120.0
0.9          NaN        9.0             NaN      120.0
(4, 5)
HADM_ID 179287
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         50.0        NaN             NaN       60.0
0.9         50.0        NaN             NaN      144.0
(9, 5)
HADM_ID 103904
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          0.0        NaN             NaN        0.0
0.9          0.0        NaN             NaN        0.0
(2, 5)
HADM_ID 114345
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         5.00        0.0             NaN        NaN
0.9       196.25       20.0             NaN        NaN
(92, 5)
HADM_ID 148158
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        100.0       10.0             NaN      114.0
0.9        100.0       10.0             NaN      226.0
(6, 5)
HADM_ID 103195
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        500.0        NaN             NaN        NaN
0.9        500.0        NaN             NaN        NaN
(1, 5)
HADM_ID 101184
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN       10.0             NaN       68.0
0.9          NaN       10.0             NaN      100.0
(6, 5)
HADM_ID 183920
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         55.0       20.0             NaN       58.0
0.9         95.0      100.0             NaN      256.0
(15, 5)
HADM_ID 151003
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN       25.0             NaN       89.0
0.9          NaN      225.0             NaN      217.0
(12, 5)
HADM_ID 155281
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN        NaN             NaN       60.0
0.9          NaN        NaN             NaN      108.0
(3, 5)
HADM_ID 150778
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          0.0        9.5             NaN       34.0
0.9         74.0       22.0             NaN       58.0
(20, 5)
HADM_ID 122293
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         50.0        NaN             NaN        NaN
0.9        230.0        NaN             NaN        NaN
(5, 5)
HADM_ID 103778
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         62.0        NaN             NaN      230.0
0.9        184.0        NaN             NaN      470.0
(17, 5)
HADM_ID 158408
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1      0.65625        3.0          0.0000        NaN
0.9     31.50000       20.0          0.1092        NaN
(252, 5)
HADM_ID 149043
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        6.125      0.475             NaN        NaN
0.9      195.000     20.000             NaN        NaN
(72, 5)
HADM_ID 112560
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1       0.4665       10.0             NaN      102.0
0.9     170.0000       30.0             NaN      340.0
(27, 5)
HADM_ID 184219
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN        0.0             NaN       48.0
0.9          NaN       20.0             NaN      112.0
(14, 5)
HADM_ID 118985
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          8.0       10.0             NaN       30.0
0.9        100.0       20.0             NaN       60.0
(65, 5)
HADM_ID 147012
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1       9.6525       0.15             NaN        NaN
0.9      19.3050      20.00             NaN        NaN
(115, 5)
HADM_ID 138331
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        300.0        5.0             NaN        NaN
0.9        300.0        5.0             NaN        NaN
(152, 5)
HADM_ID 181158
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN        NaN             NaN       90.0
0.9          NaN        NaN             NaN      244.0
(7, 5)
HADM_ID 129493
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        100.0       10.0             NaN      100.0
0.9        100.0       22.0             NaN      204.0
(54, 5)
HADM_ID 188196
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          1.5     1.9875          0.2368        NaN
0.9         28.0    15.0000          1.0440        NaN
(448, 5)
HADM_ID 168094
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          0.0       10.0             NaN      170.0
0.9        105.0       20.0             NaN      486.0
(51, 5)
HADM_ID 144017
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN       20.0             NaN        NaN
0.9          NaN       20.0             NaN        NaN
(1, 5)
HADM_ID 123912
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        150.0        NaN             NaN        NaN
0.9        350.0        NaN             NaN        NaN
(2, 5)
HADM_ID 177199
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         50.0        NaN             NaN      430.0
0.9        200.0        NaN             NaN     1338.0
(8, 5)
HADM_ID 161064
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         50.0       50.0             NaN      100.0
0.9        100.0      450.0             NaN      240.0
(14, 5)
HADM_ID 189199
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         50.0       10.0             0.0       40.0
0.9        100.0       20.0             0.0      240.0
(57, 5)
HADM_ID 166956
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         55.0       10.0             NaN       70.0
0.9         95.0       15.0             NaN      190.0
(23, 5)
HADM_ID 137772
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         6.25        0.5             NaN        NaN
0.9        50.00       20.0             NaN        NaN
(214, 5)
HADM_ID 158183
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         15.0        0.0             NaN        NaN
0.9        100.0       10.0             NaN        NaN
(47, 5)
HADM_ID 175586
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        2.285        4.0          0.2856        NaN
0.9       52.500       17.0          0.8400        NaN
(169, 5)
HADM_ID 194424
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1     9.140625       6.25           0.585        NaN
0.9   113.875000      47.70           4.095        NaN
(325, 5)
HADM_ID 148295
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1     6.000000       10.0             NaN        NaN
0.9    50.503265       10.0             NaN        NaN
(124, 5)
HADM_ID 179519
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          1.5        0.0             NaN        NaN
0.9          5.0       10.0             NaN        NaN
(206, 5)
HADM_ID 193274
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         25.0       10.0             NaN        NaN
0.9        200.0       24.5             NaN        NaN
(44, 5)
HADM_ID 114997
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1     4.770000        5.0        0.456960       12.0
0.9    57.119999       20.0        2.650368      172.0
(305, 5)
HADM_ID 186968
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         40.0       10.0             NaN       48.0
0.9        260.0       10.0             NaN      408.0
(37, 5)
HADM_ID 186821
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        250.0       10.0             NaN       50.0
0.9        250.0       20.0             NaN      240.0
(43, 5)
HADM_ID 182589
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         70.0       10.0             NaN        NaN
0.9        230.0      140.0             NaN        NaN
(18, 5)
HADM_ID 185758
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN      100.0             NaN      240.0
0.9          NaN      100.0             NaN      240.0
(2, 5)
HADM_ID 116181
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          4.0       10.0          0.3924        0.0
0.9        150.0       20.0          0.3968        0.0
(101, 5)
HADM_ID 156972
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          1.0        0.0             0.0       66.0
0.9          3.0       18.0             0.0      280.0
(46, 5)
HADM_ID 111109
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN        NaN             NaN      240.0
0.9          NaN        NaN             NaN      432.0
(3, 5)
HADM_ID 169217
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          0.0       10.0             0.0      118.0
0.9        100.0       20.0             0.0      240.0
(54, 5)
HADM_ID 122915
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         50.0        NaN             NaN      108.0
0.9        250.0        NaN             NaN      296.0
(16, 5)
HADM_ID 104329
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          6.6        5.0             NaN       30.0
0.9         60.0       10.0             NaN       30.0
(110, 5)
HADM_ID 115662
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          6.0       1.25         0.28116        NaN
0.9        500.0      10.00         0.76680        NaN
(166, 5)
HADM_ID 188392
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1      7.89375        0.0         2.02080        0.0
0.9    120.00000     1000.0         5.75928        0.0
(185, 5)
HADM_ID 169557
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         75.0        NaN             NaN        NaN
0.9         75.0        NaN             NaN        NaN
(5, 5)
HADM_ID 122982
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         50.0        5.0             NaN        NaN
0.9        150.0       10.0             NaN        NaN
(55, 5)
HADM_ID 123040
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         75.0        NaN             NaN        NaN
0.9         75.0        NaN             NaN        NaN
(6, 5)
HADM_ID 151652
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        100.0       12.0             NaN       90.0
0.9        100.0       20.0             NaN       90.0
(5, 5)
HADM_ID 170984
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1       0.9625       10.0             NaN        NaN
0.9      50.0000       33.0             NaN        NaN
(58, 5)
HADM_ID 190582
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN        NaN             NaN      120.0
0.9          NaN        NaN             NaN      120.0
(1, 5)
HADM_ID 107286
     DEXTROSE 5%   NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          5.0  166.600006             0.0      130.0
0.9         45.0  166.600006             0.0      300.0
(8, 5)
HADM_ID 148365
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          0.0        0.0             0.0        0.0
0.9        300.0       10.0             0.0        0.0
(62, 5)
HADM_ID 102847
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          0.0      0.325             NaN        NaN
0.9         40.0     12.500             NaN        NaN
(47, 5)
HADM_ID 173681
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1    18.750000       10.0          0.5625      120.0
0.9   108.072914       20.0          3.7500      120.0
(154, 5)
HADM_ID 111970
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          0.4        5.0         0.03072        NaN
0.9         12.0       10.0         0.09984        NaN
(85, 5)
HADM_ID 149844
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         75.0        NaN             NaN      400.0
0.9        750.0        NaN             NaN      400.0
(8, 5)
HADM_ID 135251
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN        NaN             NaN      125.0
0.9          NaN        NaN             NaN      325.0
(3, 5)
HADM_ID 156400
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          0.0       15.5        0.000000      246.0
0.9        250.0      200.0        1.400923      600.0
(163, 5)
HADM_ID 171681
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        500.0       10.0             NaN        9.0
0.9        500.0       10.0             NaN       81.0
(47, 5)
HADM_ID 189051
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         10.0        4.0         0.62682       75.0
0.9         50.0       20.0         2.00178       75.0
(152, 5)
HADM_ID 162875
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN        NaN             NaN      100.0
0.9          NaN        NaN             NaN      100.0
(1, 5)
HADM_ID 160080
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        100.0       10.0             NaN      140.0
0.9        235.0       10.0             NaN      480.0
(40, 5)
HADM_ID 147319
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        100.0       20.0             NaN      204.0
0.9        100.0       20.0             NaN      236.0
(5, 5)
HADM_ID 153858
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1     12.92625       10.0        0.413640        NaN
0.9    100.00000      500.0        0.715856        NaN
(164, 5)
HADM_ID 171106
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         75.0        5.0             NaN        NaN
0.9        375.0        5.0             NaN        NaN
(53, 5)
HADM_ID 150506
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN        0.0             NaN      120.0
0.9          NaN        0.0             NaN      410.0
(7, 5)
HADM_ID 121097
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        100.0       10.0             NaN      118.0
0.9        130.0       10.0             NaN      240.0
(40, 5)
HADM_ID 170106
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         50.0       10.0             NaN      120.0
0.9         90.0       20.0             NaN      240.0
(34, 5)
HADM_ID 147119
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          1.0       10.0        0.276360        NaN
0.9        100.0       10.0        0.959364        NaN
(116, 5)
HADM_ID 175912
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         50.0       10.0             NaN        NaN
0.9        150.0       20.0             NaN        NaN
(81, 5)
HADM_ID 151808
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          3.0       10.0             NaN      120.0
0.9         37.5       10.0             NaN      120.0
(67, 5)
HADM_ID 189131
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN        NaN             NaN      120.0
0.9          NaN        NaN             NaN      120.0
(1, 5)
HADM_ID 104141
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        100.0        NaN             NaN      220.0
0.9        100.0        NaN             NaN      380.0
(4, 5)
HADM_ID 105557
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN       10.0             NaN        NaN
0.9          NaN       10.0             NaN        NaN
(3, 5)
HADM_ID 154361
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1    13.700125        NaN        0.346312       21.0
0.9   550.000000        NaN        0.482088       29.0
(27, 5)
HADM_ID 146426
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         50.0       10.0             NaN        NaN
0.9        155.0       10.0             NaN        NaN
(60, 5)
HADM_ID 159459
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN       10.0             NaN      108.0
0.9          NaN       20.0             NaN      272.0
(29, 5)
HADM_ID 195303
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN       49.5             NaN      195.0
0.9          NaN      325.5             NaN      360.0
(9, 5)
HADM_ID 134462
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        500.0       10.0             NaN      120.0
0.9        500.0       10.0             NaN      120.0
(10, 5)
HADM_ID 146738
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1     0.000000        0.4          0.3726        0.0
0.9   122.373756      105.0          1.7388        0.0
(326, 5)
HADM_ID 108445
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        100.0       50.0             NaN        NaN
0.9        300.0       68.0             NaN        NaN
(22, 5)
HADM_ID 151700
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         10.0        NaN             NaN        NaN
0.9        304.0        NaN             NaN        NaN
(5, 5)
HADM_ID 157222
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         42.5       10.0             NaN        NaN
0.9        300.0       10.0             NaN        NaN
(56, 5)
HADM_ID 161583
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        100.0       10.0             NaN        NaN
0.9        160.0       10.0             NaN        NaN
(9, 5)
HADM_ID 164020
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        19.95        4.0             NaN      144.0
0.9        55.00       20.0             NaN      240.0
(186, 5)
HADM_ID 199231
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN       20.0             NaN        NaN
0.9          NaN       20.0             NaN        NaN
(1, 5)
HADM_ID 105098
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          0.0       10.0             0.0        NaN
0.9        170.0       20.0             0.0        NaN
(11, 5)
HADM_ID 155044
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          5.0        0.5             NaN        NaN
0.9         10.0        5.0             NaN        NaN
(66, 5)
HADM_ID 155456
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         49.8       10.0             NaN      150.0
0.9        200.0      150.0             NaN      240.0
(41, 5)
HADM_ID 112223
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         50.0       10.0             NaN       71.0
0.9        365.0       10.0             NaN      240.0
(35, 5)
HADM_ID 187271
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN        NaN             NaN       40.0
0.9          NaN        NaN             NaN      125.0
(6, 5)
HADM_ID 181250
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          5.4       2.25             NaN        NaN
0.9         50.0    1000.00             NaN        NaN
(41, 5)
HADM_ID 194188
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          NaN       20.0             NaN      480.0
0.9          NaN       20.0             NaN      480.0
(2, 5)
HADM_ID 160804
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        115.0        NaN             NaN        5.0
0.9        235.0        NaN             NaN        5.0
(3, 5)
HADM_ID 178931
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1        100.0       10.0             NaN        NaN
0.9        100.0       20.0             NaN        NaN
(41, 5)
HADM_ID 105931
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1     3.414375       10.0         0.10926      115.0
0.9   400.000000       56.0         0.23673      235.0
(160, 5)
HADM_ID 165406
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1         10.0        4.0             NaN        NaN
0.9        100.0       10.0             NaN        NaN
(98, 5)
HADM_ID 125303
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0.1          7.0       20.0             NaN        NaN
0.9         25.0       30.0             NaN        NaN
(143, 5)
HADM_ID 114540
     DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE

In [81]:
ot=pd.concat(ck)
ot.shape

(17745, 5)

In [82]:
ot.isna().sum()

HADM_ID               0
DEXTROSE 5%       14111
NACL 0.9%         14695
NOREPINEPHRINE    16903
PO INTAKE         17583
dtype: int64

In [83]:
ot.head()

  HADM_ID  DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0  172260          NaN        NaN             NaN        NaN
1  172260          NaN        NaN             NaN        NaN
2  172260          NaN        NaN             NaN        NaN
3  172260         35.0        NaN             NaN        NaN
4  172260          NaN        NaN             NaN        NaN

In [84]:
ot.describe()

       DEXTROSE 5%    NACL 0.9%  NOREPINEPHRINE   PO INTAKE
count  3634.000000  3050.000000      842.000000  162.000000
mean     47.591260    37.300990        1.316402  168.641975
std      78.186898    88.428032        1.795705  114.057064
min       0.332973     0.300000        0.002100   30.000000
25%       9.421625     5.000000        0.393675  100.000000
50%      24.412500    10.000000        0.743921  120.000000
75%      50.000000    20.000000        1.321200  215.000000
max     999.999974  1000.000000       15.814402  960.000000

In [85]:
LIST = ['DEXTROSE 5%',  
         'NACL 0.9%', 'NOREPINEPHRINE', 'PO INTAKE']

In [86]:
for i in LIST:
    ot[i] = ot[i].fillna(ot.groupby(['HADM_ID'])[i].transform('mean'))
    ot[i] = ot.groupby(['HADM_ID'])[i].transform('mean')

In [87]:
ot = ot.drop_duplicates(['HADM_ID'], keep='first')

In [88]:
ot.shape

(348, 5)

In [89]:
ot.describe()

       DEXTROSE 5%   NACL 0.9%  NOREPINEPHRINE   PO INTAKE
count   165.000000  145.000000       59.000000   50.000000
mean     80.328982  107.061572        1.401905  167.534524
std      74.478241  151.843133        1.516521  109.662176
min       2.000000    0.813636        0.024214   40.000000
25%      24.959782   10.000000        0.507017  111.250000
50%      50.858766   35.849408        0.893777  145.833333
75%     104.851634  145.113636        1.658964  200.000000
max     414.511760  683.833347        7.995745  730.000000

In [90]:
ot.head()

    HADM_ID  DEXTROSE 5%  NACL 0.9%  NOREPINEPHRINE  PO INTAKE
0    172260    23.563756       15.0             NaN        NaN
135  146995          NaN      600.0             NaN        NaN
141  193149          NaN        NaN             NaN        NaN
145  179287          NaN        NaN             NaN      115.0
154  103904          NaN        NaN             NaN        NaN

In [91]:
ot.isna().sum()

HADM_ID             0
DEXTROSE 5%       183
NACL 0.9%         203
NOREPINEPHRINE    289
PO INTAKE         298
dtype: int64

In [92]:
ot.to_csv("Input1.csv")